[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "divvy_analysis"
version = "0.0.1"
description = "Comprehensive analysis of Divvy bike-sharing unit economics and market dynamics"
authors = [
  { name = "The Irony of Fate" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["divvy_analysis"]
include = ["pyproject.toml", "divvy_analysis/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["divvy_analysis"]
force-sort-within-sections = true

