services:
  my_pg:
    image: ghcr.io/hasura/ndc-postgres:v3.1.0  # ИЗМЕНЕНО: правильный тег
    ports:
      - "8100:8080"
    environment:
      JDBC_URL: jdbc:postgresql://localhost:5433/dev
      USER: user
      PASSWORD: password
      SSL_MODE: disable
      JDBC_SCHEMAS: public
